Predicting the possibility of heart disease

## 1.Problem Definition
With the give data we have to predict whether the person is having heart disease or not
## 2.Data Definition
This is a multivariate type of dataset which means providing or involving a variety of separate mathematical or statistical variables, multivariate numerical data analysis. It is composed of 14 attributes which are age, sex, chest pain type, resting blood pressure, serum cholesterol, fasting blood sugar, resting electrocardiographic results, maximum heart rate achieved, exercise-induced angina, oldpeak â€” ST depression induced by exercise relative to rest, the slope of the peak exercise ST segment, number of major vessels and Thalassemia. This database includes 76 attributes, but all published studies relate to the use of a subset of 14 of them. The Cleveland database is the only one used by ML researchers to date. One of the major tasks on this dataset is to predict based on the given attributes of a patient that whether that particular person has heart disease or not and other is the experimental task to diagnose and find out various insights from this dataset which could help in understanding the problem more.

DATA LINK:https://archive.ics.uci.edu/dataset/45/heart+disease

Project's goal is to contribute to the development of effective risk stratification tools that can assist healthcare providers in delivering personalized care and improving patient outcomes in the field of cardiology.

Link to CSV FILE : https://docs.google.com/spreadsheets/d/1Wb0LNUOFUY3xeRK4wKSrx-kwmLYRdl8pnRTnaqRRLvc/edit?usp=sharing


Heart disease is a significant public health concern worldwide, contributing to millions of deaths annually. As a student, selecting heart disease prediction as a project topic for an assignment provides an opportunity to delve into a critical area of healthcare and contribute to the advancement of predictive analytics in medicine.

Heart disease encompasses various conditions affecting the heart and blood vessels, including coronary artery disease, heart failure, arrhythmias, and congenital heart defects. Early detection and accurate prediction of heart disease risk factors are crucial for implementing preventive measures and improving patient outcomes.

The project will also explore the ethical implications of using predictive analytics in healthcare, including issues related to data privacy, algorithm transparency, and equitable access to healthcare services. By addressing these concerns, the project aims to develop a robust and ethically responsible predictive model for heart disease prediction.

## 3 Evaluation
We need 95%+ accuracy to pursue with this project
## 4.Features details
We can refer to the data link given above for the features details

## Preparing the tools

In [ ]:
#EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#Models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

#ModelEvaluation
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV,cross_val_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import RocCurveDisplay
from sklearn import metrics

#Saving model
import pickle
import warnings

# Suppress all warnings
warnings.filterwarnings('ignore')

In [ ]:
#Loading the data
hd=pd.read_csv("heart-disease.csv")
hd

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0